using System.ComponentModel;
using ModelContextProtocol.Extensions.Apps;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace Mcp.Ui;

[McpServerResourceType]
public class UiResources
{
    private readonly IUiCacheService _uiCacheService;

    public UiResources(IUiCacheService uiCacheService)
    {
        _uiCacheService = uiCacheService;
    }

    [McpServerResource(UriTemplate = UiTools.ExplorerUri, Name = "Bookmark Explorer UI", MimeType = McpApps.HtmlMimeType)]
    [Description("Returns the HTML grid generated by the most recent bookmark visualization request.")]
    public TextResourceContents GetExplorerUi()
    {
        var html = _uiCacheService.GetHtml(UiTools.ExplorerUri);

        if (html == null)
        {
            return new TextResourceContents
            {
                Uri = UiTools.ExplorerUri,
                MimeType = McpApps.HtmlMimeType,
                Text = "<html><body><h2>Error</h2><p>UI visualization not found or expired.</p></body></html>"
            };
        }

        return new TextResourceContents
        {
            Uri = UiTools.ExplorerUri,
            MimeType = McpApps.HtmlMimeType,
            Text = html
        };
    }
}
